### ISSUE TITLE
Unsupported argument on provider.tf line 8 sensitive is not expected here.

### ISSUE THREAD

**Issue by SquaredLoops** [hashicorp/tfc-getting-started#12]
In PR #5 the `sensitive` flag was added to the `provider.tf` file, however that feature was added in Terraform `0.14`.

The `readme.md` and `scripts/setup.sh` specify that Terraform `0.13` or above is required, not `0.14`.

If you run the `setup.sh` script while running Terraform `0.13.x` then you will receive the following error:
```bash
Error: Unsupported argument

  on provider.tf line 8, in variable "provider_token":
   8:   sensitive = true

An argument named "sensitive" is not expected here.
```

The quick solution is to either remove line 8 (containing `sensitive = true`) or to upgrade to Terraform `0.14.x`.

The best fix is to update the `readme.md` and `setup.sh` to specify / check for `0.14`.

**Comment by pwalters04** [comment]
Same. I have received the same issue for Terraform `0.13`and used the same workaround of commenting/removing it out.

`tfc-getting-started on  main  took 31s 
➜ terraform init 
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported argument

  on provider.tf line 8, in variable "provider_token":
   8:   sensitive = true

An argument named "sensitive" is not expected here.`

**Comment by barrettclark** [comment]
The project has been updated for a minimum version of `0.14` thanks to #13
